pipeline {
    agent any

    tools {
        python 'Python3'
    }

    environment {
        GIT_REPO = 'https://github.com/BBBenson/alx-backend-python.git'
    }

    

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: "${env.GIT_REPO}",
                    credentialsId: 'github-creds'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest messaging_app/tests/ --junitxml=report.xml'
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
                stage('Build Docker Image') {
            steps {
                script {
                    docker.build("your-dockerhub-username/messaging_app:${BUILD_NUMBER}", "messaging_app")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        docker.image("your-dockerhub-username/messaging_app:${BUILD_NUMBER}").push()
                        docker.image("your-dockerhub-username/messaging_app:${BUILD_NUMBER}").push("latest")
                    }
                }
            }
        }

    }
}
